### PR TITLE
Check that /usr/local/{bin,sbin} exist and are writeable

### PR DESCRIPTION
**Pull request by pianohacker**

### CODE REVIEW

**Comment by fabiomaia** [comment]
Thank you!

Why wouldn't they exist or be writeable?

**Comment by pianohacker** [comment]
`/usr/local/sbin` specifically did not exist on either of the Macs I tried this script on; I did `bin` for completeness.

(Thanks for this tool, by the way! Works a treat.)

**Comment by fabiomaia** [comment]
More importantly, did the script initially fail because of this?

**Comment by pianohacker** [comment]
Yes; while installing openssh, it tries to install sshd to /usr/local/sbin and fails.

**Comment by fabiomaia** [comment]
Hmm, I don't recall ever running into this, but I guess it wouldn't hurt to add this either. I'll let this sink in for a bit before merging.

**Pull request merged**
